[package]
name = "port-scanner"
version = "0.1.0"
authors = ["0xreself <lars.m.schneider2002@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
